import "@/app/index.css";
import "@/app/globals.css";
import Link from "next/link";
import { getFolioByID } from "@/services/folio";
import { getAuthedUser, getAuthedUserID, getUserByID } from "@/services/user";
import Image from "next/image";
import { date } from "@/utils/date";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  const { id } = params;
  const folio = await getFolioByID(id);
  const folioOwner = await getUserByID(folio?.user_id || "");
  const authedUser = await getAuthedUser();
  return (
    <div>
      <main className="w-full min-h-screen p-12">{children}</main>
      <footer className="flex justify-between items-center p-6 border-t border-skeleton shadow-lg">
        {!!folioOwner && (
          <div className=" flex items-center gap-2 ">
            <Image
              src={folioOwner.profile_avatar || ""}
              alt="Folio Owner"
              width={50}
              height={50}
              className="rounded-full object-center"
            />
            <Link href={`/profile/${folioOwner.id}`}>
              <span className="font-semibold underline text-dimmed">
                @{folioOwner.username}
              </span>
            </Link>
          </div>
        )}
        <div className="text-sm font-semibold text-dimmed">
          {date.format(folio?.created_at)}
        </div>
      </footer>
    </div>
  );
}
