import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./index.css";
import ProvidersWrapper from "./ProvidersWrapper";
import logo from "@/public/logo/black-white.png";
const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  mx-auto`}>
        
        <ProvidersWrapper>{children}</ProvidersWrapper>
        <footer className="p-6 bg-black text-white space-y-8">
          <Link href="/">
            <Image alt="Image" src={logo} width={50} height={50} />
          </Link>
          <div className="flex flex-wrap gap-20">
            <div className=" text-sm">
              <span className="font-semibold">Me</span>
              <ul className=" text-neutral-400">
                <li>Dashboard</li>
                <li>Messages</li>
                <li>Growth</li>
              </ul>
            </div>
            <div className=" text-sm">
              <span className="font-semibold">Me</span>
              <ul className=" text-neutral-400">
                <li>Dashboard</li>
                <li>Messages</li>
                <li>Growth</li>
              </ul>
            </div>
            <div className=" text-sm">
              <span className="font-semibold">Me</span>
              <ul className=" text-neutral-400">
                <li>Dashboard</li>
                <li>Messages</li>
                <li>Growth</li>
              </ul>
            </div>
            <div className=" text-sm">
              <span className="font-semibold">Me</span>
              <ul className=" text-neutral-400">
                <li>Dashboard</li>
                <li>Messages</li>
                <li>Growth</li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
