import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import '../index.css'
import Navbar from '@/components/Navbar/navbar.index'
import Footer from '@/components/Footer/footer.index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={`${inter.className}  mx-auto`} >
        <Navbar />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
