import "@/app/index.css";
import "@/app/globals.css";
import Sidebar from "./components/sidebar/Sidebar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex ">
      <Sidebar />
      <div className="w-full p-12">
        {children}
      </div>
    </div>
  );
}
